name: wcl github actions workflow
on:
  workflow_call:
jobs:
  echo_msg:
    name: echo msg
    # runs-on: ubuntu-latest
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: show msg
        run: |
        echo "hello world"
